/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_assignment1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Frame_Forum_View_Topic extends javax.swing.JFrame {

    private String userrr;

    /**
     * Creates new form Frame_Forum_View_Topic
     */
    public Frame_Forum_View_Topic() {
        initComponents();
        showUser();
    }

    public Frame_Forum_View_Topic(String course, String sub, String forumidd, String topicc, String des) {
        initComponents();
        showUser();
        coursetxt.setText(course);
        subtxt.setText(sub);
        forumidtxt.setText(forumidd);
        topictxt.setText(topicc);
        descriptiontxt.setText(des);
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        forumidtxt = new javax.swing.JLabel();
        topictxt = new javax.swing.JLabel();
        descriptiontxt = new javax.swing.JLabel();
        coursetxt = new javax.swing.JLabel();
        subtxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commenttable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commenttxt = new javax.swing.JTextArea();
        deletebtn = new javax.swing.JButton();
        commentttt = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel2.setText("FORUM");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_assignment1/logo.png"))); // NOI18N

        jLabel4.setText("Forum ID");

        jLabel5.setText("Topic");

        jLabel7.setText("Description");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        forumidtxt.setText("jLabel1");

        topictxt.setText("jLabel1");

        descriptiontxt.setText("jLabel1");

        coursetxt.setText("jLabel1");

        subtxt.setText("jLabel1");

        jLabel8.setText("Course");

        jLabel9.setText("Sub Forum");

        commenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comment", "User"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        commenttable.getTableHeader().setReorderingAllowed(false);
        commenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commenttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(commenttable);

        jLabel1.setText("Add Comment");

        commenttxt.setColumns(20);
        commenttxt.setRows(5);
        jScrollPane2.setViewportView(commenttxt);

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        commentttt.setText("Comment");
        commentttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commenttttActionPerformed(evt);
            }
        });

        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(commentttt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(coursetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(topictxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(forumidtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(descriptiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 224, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coursetxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forumidtxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(topictxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(descriptiontxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commentttt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Frame_Forum_View ffv = new Frame_Forum_View();
        ffv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String course = coursetxt.getText();
        String sub = subtxt.getText();
        String forumidd = forumidtxt.getText();
        String topicc = topictxt.getText();
        String des = descriptiontxt.getText();
        String commentt = commenttxt.getText();
        String user = showUser();
        Comment cc = new Comment();
        int count = cc.delete(course, sub, forumidd, topicc, des, user, commentt);
        switch (count) {
            case 1:
                //JOptionPane.showMessageDialog(null, "Forum Added!");
                commenttxt.setText(null);
                DefaultTableModel dm = (DefaultTableModel) commenttable.getModel();
                while (dm.getRowCount() > 0) {
                    dm.removeRow(0);
                }
                showTable();
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Delete fail, please try again");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void commenttttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commenttttActionPerformed
        String course = coursetxt.getText();
        String sub = subtxt.getText();
        String forumidd = forumidtxt.getText();
        String topicc = topictxt.getText();
        String des = descriptiontxt.getText();
        String commentt = commenttxt.getText();
        String user = showUser();
        Comment cc = new Comment();
        int count = cc.post(course, sub, forumidd, topicc, des, user, commentt);
        switch (count) {
            case 1:
                //JOptionPane.showMessageDialog(null, "Forum Added!");
                commenttxt.setText(null);
                DefaultTableModel dm = (DefaultTableModel) commenttable.getModel();
                while (dm.getRowCount() > 0) {
                    dm.removeRow(0);
                }
                showTable();
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Add fail, please try again");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_commenttttActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        String course = coursetxt.getText();
        String sub = subtxt.getText();
        String forumidd = forumidtxt.getText();
        String topicc = topictxt.getText();
        String des = descriptiontxt.getText();
        String commentt = commenttxt.getText();
        String user = showUser();
        Comment cc = new Comment();
        int count = cc.edit(course, sub, forumidd, topicc, des, user, commentt);
        switch (count) {
            case 1:
                //JOptionPane.showMessageDialog(null, "Forum Added!");
                commenttxt.setText(null);
                DefaultTableModel dm = (DefaultTableModel) commenttable.getModel();
                while (dm.getRowCount() > 0) {
                    dm.removeRow(0);
                }
                showTable();
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Edit fail, please try again");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_editbtnActionPerformed

    private void commenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commenttableMouseClicked
        String user = showUser();
        commenttxt.setText(null);
        Database database = new Database();
        database.getAllData();;
        ArrayList<Comment> comment = database.getComment();
        DefaultTableModel model = (DefaultTableModel) commenttable.getModel();
        int selectedRowIndex = commenttable.getSelectedRow();
        for (int i = 0; i < comment.size(); i++) {
            if (comment.get(i).getUsers().equals(user) && comment.get(i).getComments().equals(model.getValueAt(selectedRowIndex, 0).toString())) {
                //System.out.println(comment.get(i).getUsers());              
                commenttxt.setText(model.getValueAt(selectedRowIndex, 0).toString());              
            }
        }
        //commenttxt.setText(null);

    }//GEN-LAST:event_commenttableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Forum_View_Topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Forum_View_Topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Forum_View_Topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Forum_View_Topic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Forum_View_Topic().setVisible(true);
            }
        });
    }

    public String showUser() {
        Database database = new Database();
        database.getAllData();
        try {
            ArrayList<User> userList = database.getUser();
            int size = userList.size();
            for (int i = 0; i < size; i++) {
                this.userrr = userList.get(i).getUsername();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Profile Error, " + e);
        }
        return userrr;
    }

    public void showTable() {
        Database database = new Database();
        database.getAllData();;
        ArrayList<Comment> comment = database.getComment();
        DefaultTableModel model = (DefaultTableModel) commenttable.getModel();
        Object[] row = new Object[2];
        for (int i = 0; i < comment.size(); i++) {
            if (comment.get(i).getForumID().equals(forumidtxt.getText()) && comment.get(i).getTopic().equals(topictxt.getText())) {
                row[0] = comment.get(i).getComments();
                row[1] = comment.get(i).getUsers();
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTable commenttable;
    private javax.swing.JButton commentttt;
    private javax.swing.JTextArea commenttxt;
    private javax.swing.JLabel coursetxt;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel descriptiontxt;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel forumidtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel subtxt;
    private javax.swing.JLabel topictxt;
    // End of variables declaration//GEN-END:variables

}
