/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_assignment1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Frame_Add_Course extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Add_Course
     */
    public Frame_Add_Course() {
        initComponents();
        list();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yearscmb = new javax.swing.JComboBox<>();
        programmeok = new javax.swing.JButton();
        yearok = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        semestercmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        programmgecmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseIDtxt = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        courseNametxt = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        credittxt = new javax.swing.JTextPane();
        resetbtn = new javax.swing.JButton();
        bckbtn = new javax.swing.JButton();
        registerbtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        descriptiontxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_assignment1/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel2.setText("ADD COURSE");

        programmeok.setText("SELECT");
        programmeok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programmeokActionPerformed(evt);
            }
        });

        yearok.setText("SELECT");
        yearok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearokActionPerformed(evt);
            }
        });

        jLabel4.setText("Semesters:");

        jLabel1.setText("Programme: ");

        jLabel3.setText("Years");

        jLabel5.setText("Course ID:");

        jLabel7.setText("Course Name:");

        jLabel8.setText("Description:");

        jLabel9.setText("Credit Hour");

        jScrollPane1.setViewportView(courseIDtxt);

        jScrollPane2.setViewportView(courseNametxt);

        jScrollPane4.setViewportView(credittxt);

        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        bckbtn.setText("Back");
        bckbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckbtnActionPerformed(evt);
            }
        });

        registerbtn.setText("Register");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        descriptiontxt.setColumns(20);
        descriptiontxt.setRows(5);
        jScrollPane5.setViewportView(descriptiontxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bckbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2)
                                    .addComponent(programmgecmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yearscmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(semestercmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(programmeok)
                            .addComponent(yearok))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(programmgecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(programmeok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(yearscmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(semestercmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(registerbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetbtn)
                    .addComponent(bckbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void programmeokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programmeokActionPerformed
        yearscmb.removeAllItems();
        yearscmb.addItem("- Please Select -");
        yearscmb.setSelectedItem("- Please Select -");
        String choice = programmgecmb.getSelectedItem().toString();

        Database database = new Database();
        database.getAllData();

        try {
            ArrayList<ProgrammeStructure> progsList = database.getProgrammeStructure();
            int size = progsList.size();
            for (int i = 0; i < size; i++) {
                if (progsList.get(i).getProgrammeCode().equals(choice)) {
                    yearscmb.addItem(progsList.get(i).getAcademicYear());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Year list Error, " + e);
        }
    }//GEN-LAST:event_programmeokActionPerformed

    private void yearokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearokActionPerformed
        semestercmb.removeAllItems();
        semestercmb.addItem("- Please Select -");
        semestercmb.setSelectedItem("- Please Select -");
        String choices = yearscmb.getSelectedItem().toString();

        Database database = new Database();
        database.getAllData();

        try {
            ArrayList<ProgrammeStructure> progsList = database.getProgrammeStructure();
            int size = progsList.size();
            for (int i = 0; i < size; i++) {
                if (progsList.get(i).getProgrammeCode().equals(programmgecmb.getSelectedItem().toString()) && progsList.get(i).getAcademicYear().equals(choices)) {
                    semestercmb.addItem(progsList.get(i).getSemesters());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Year list Error, " + e);
        }
    }//GEN-LAST:event_yearokActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        verify();
        String programme = programmgecmb.getSelectedItem().toString();
        String courseID = courseIDtxt.getText();
        String courseName = courseNametxt.getText();
        String description = descriptiontxt.getText();
        String credit = credittxt.getText();

        Course course = new Course();
        int count = course.addCourse(programme, courseID, courseName, description, credit);
        switch (count) {
            case 1:
                JOptionPane.showMessageDialog(null, "Add Success!");
                rst();
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Add fail, please try again");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_registerbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        rst();
    }//GEN-LAST:event_resetbtnActionPerformed

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
        Frame_Admin_Course fac = new Frame_Admin_Course();
        this.setVisible(false);
        fac.setVisible(true);
    }//GEN-LAST:event_bckbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Add_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Add_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Add_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Add_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Add_Course().setVisible(true);
            }
        });
    }

    public void list() {
        programmgecmb.addItem("- Please Select -");
        programmgecmb.setSelectedItem("- Please Select -");

        Database database = new Database();
        database.getAllData();

        try {
            ArrayList<Programme> progList = database.getProgramme();
            int size = progList.size();
            for (int i = 0; i < progList.size(); i++) {
                programmgecmb.addItem(progList.get(i).getProgrammeCode());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Programme list Error, " + e);
        }
    }

    public void verify() {
        if (courseIDtxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Course ID is empty!");
        } else if (courseNametxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Course Name is empty!");
        } else if (descriptiontxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Description is empty!");
        } else if (credittxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Credit Hour is empty!");
        }
    }
    
    public void rst(){
        list();
        yearscmb.removeAllItems();
        semestercmb.removeAllItems();
        courseIDtxt.setText(null);
        courseNametxt.setText(null);
        descriptiontxt.setText(null);
        credittxt.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckbtn;
    private javax.swing.JTextPane courseIDtxt;
    private javax.swing.JTextPane courseNametxt;
    private javax.swing.JTextPane credittxt;
    private javax.swing.JTextArea descriptiontxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton programmeok;
    private javax.swing.JComboBox<String> programmgecmb;
    private javax.swing.JButton registerbtn;
    private javax.swing.JButton resetbtn;
    private javax.swing.JComboBox<String> semestercmb;
    private javax.swing.JButton yearok;
    private javax.swing.JComboBox<String> yearscmb;
    // End of variables declaration//GEN-END:variables
}
